### ISSUE TITLE
Error on face_recognize.py

### ISSUE THREAD

**Issue by imranulbari** [abdullah-K/face-recognition#1]
I am facing an error while running this on anaconda virtual env. I have set the location for .xml and faces directory accordingly. Training was done correctly but got error as below while running face_recognize.py

_```
(opencv) C:\Users\simran\AppData\Roaming\.homeassistant\opencv\face-recognition>python face_recognize.py
  File "face_recognize.py", line 61
    cv2.putText(im,'%s' % (names[prediction[0]]),(x + 10, (y + 22) + h), cv2.FONT_HERSHEY_PLAIN,1.5,(20,205,20), 2)
                                                                                                                  ^
```_

**Comment by abdullah-K** [comment]
Did you get this fixed? I'm quite sorry for not replying, I never saw this issue pop up anywhere @imranulbari

**Comment by soorajbhatt** [comment]
@imranulbari try to remove space of line start from - cv2.putText(im,'%s' % (names[prediction[0]]),(x + 10, (y + 22) + h), cv2.FONT_HERSHEY_PLAIN,1.5,(20,205,20), 2)
than press spacebar to indent it.

i had same problem and resolved using above step.

same for line 63.

Hope it works.
